apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: digital-twin

build:
  artifacts:
    - image: ghcr.io/celine-eu/digital-twin
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useDockerCLI: true
  tagPolicy:
    sha256: {}
