version: "3"

tasks:
  run:
    desc: Run
    cmds:
      - uv run uvicorn celine.dt.main:create_app --reload
  test:
    desc: Run tests
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags

  dump-source:
    cmds:
      - uv run python scripts/dump_source.py

  alembic:migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  alembic:sync-model:
    desc: "Create new revision"
    cmds:
      - uv run alembic revision --autogenerate -m \"$MSG\"
    vars:
      MSG: "update model"

  alembic:reset:
    desc: "Reset DB schema"
    cmds:
      - uv run alembic downgrade base
