version: "3"

tasks:
  setup:
    desc: Setup environment
    cmds:
      - uv sync

  run:
    desc: Run
    cmds:
      - CELINE_ENV=${CELINE_ENV:-dev} .venv/bin/uvicorn celine.dt.main:create_app --factory --reload --host 0.0.0.0 --port 8002

  debug:
    desc: "Run development server with debugger"
    cmds:
      - CELINE_ENV=${CELINE_ENV:-dev} LOG_LEVEL=DEBUG .venv/bin/python -m debugpy --listen 0.0.0.0:48002 -m uvicorn celine.dt.main:create_app --factory --host 0.0.0.0 --port 8002

  test:
    desc: Run tests
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags
